# Generated by Django 5.2.4 on 2025-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name_first',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_last',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
