# Generated by Django 5.2.4 on 2025-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='receipt_image',
            field=models.ImageField(upload_to='payment_receipts/'),
        ),
    ]
