# Generated by Django 5.2.4 on 2025-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
